modLoader="javafml"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/BloCamLimb/ModernUI/issues"
logoFile= "modernui_logo.png"
license="Multi-licensing, see https://github.com/BloCamLimb/ModernUI for details"

[[mods]]
    modId="modernui"
    version="${version}"
    displayName="Modern UI"
    displayURL="https://curseforge.com/minecraft/mc-mods/modern-ui"
    authors="BloCamLimb"
    description='''
    Modern desktop framework from low-level 3D graphics API to high-level view model, for development of 2D/3D rendering software or game engine, with internationalization support and many new technologies.
    Modern UI is a desktop application framework designed for standalone 2D and 3D rendering software development. It makes use of modern 3D graphical APIs and technologies to provide high real-time rendering performance. For good measure, Modern UI improves and optimizes a set of features used by Android and its own set of internationalization supporting text layout engine meeting Unicode specification.
    This version is an official version that extends to Minecraft and Forge, which combines Modern UI with Minecraft and provides a large number of additional features and modding APIs.
    '''

[[dependencies.modernui]]
    modId="forge"
    mandatory=true
    versionRange="[39.1.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.modernui]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1, 1.19)"
    ordering="NONE"
    side="BOTH"
